"""add cover_photo to user

Revision ID: 16920fe072ef
Revises: 2ebeb933bade
Create Date: 2026-04-24 20:17:21.577304

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16920fe072ef'
down_revision = '2ebeb933bade'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cover_photo', sa.String(length=256), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('cover_photo')

    # ### end Alembic commands ###
