"""add service_professional association

Revision ID: 176f6de28fc6
Revises: 00cc77d3e1d8
Create Date: 2025-06-09 08:00:10.964520

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '176f6de28fc6'
down_revision = '00cc77d3e1d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service_professional',
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('professional_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['professional_id'], ['professional.id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['service.id'], ),
    sa.PrimaryKeyConstraint('service_id', 'professional_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('service_professional')
    # ### end Alembic commands ###
