"""Ajuste cad user

Revision ID: f7325e9c937a
Revises: dfd980e40cf7
Create Date: 2025-10-19 08:53:47.839690

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7325e9c937a'
down_revision = 'dfd980e40cf7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('full_name', sa.String(length=128), nullable=False))
        batch_op.add_column(sa.Column('company_name', sa.String(length=64), nullable=False))
        batch_op.add_column(sa.Column('phone', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('cep', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('logradouro', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('numero', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('cidade', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('estado', sa.String(length=2), nullable=True))
        batch_op.add_column(sa.Column('profile_photo', sa.String(length=256), nullable=True))
        batch_op.add_column(sa.Column('plan', sa.String(length=32), nullable=True))
        batch_op.create_unique_constraint(None, ['company_name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('plan')
        batch_op.drop_column('profile_photo')
        batch_op.drop_column('estado')
        batch_op.drop_column('cidade')
        batch_op.drop_column('numero')
        batch_op.drop_column('logradouro')
        batch_op.drop_column('cep')
        batch_op.drop_column('phone')
        batch_op.drop_column('company_name')
        batch_op.drop_column('full_name')

    # ### end Alembic commands ###
